### ISSUE TITLE
Upgrade the recommended root version  

### ISSUE THREAD

**Issue by amanmdesai** [hsf-training/hsf-training-cms-analysis#12]
Reasons:

* I could not find the current recommended root version from the website (https://hub.docker.com/r/rootproject/root)
* The current root version 6.18 is too old (latest is 6.26); oldest available is 6.20
* Will try to check the analysis codes with #11 using different root version

Need to upgrade the corresponding tutorials elsewhere to reflect this change.

**Comment by amanmdesai** [comment]
From the tests: we can upgrade to one of the following versions: 

* 6.22.08-conda  OR
* 6.24.06-conda  OR
* latest 

Let me know which one, and then I can update the corresponding information in readme/setup in this repo as well as the cms webpage repo

**Comment by klieret** [comment]
Unfortunately I'm not very familiar with ROOT

@oshadura : Is there any reason not to just use the version from the `rootproject/root:latest` container? It's a stable build, right?

**Comment by klieret** [comment]
> I could not find the current recommended root version from the website ([hub.docker.com/r/rootproject/root](https://hub.docker.com/r/rootproject/root))

But isn't that what the `latest -> 6.26...` line tells us on top?

**Comment by amanmdesai** [comment]
> > I could not find the current recommended root version from the website ([hub.docker.com/r/rootproject/root](https://hub.docker.com/r/rootproject/root))
> 
> But isn't that what the `latest -> 6.26...` line tells us on top?

I meant the current version recommended by the HSF CMS Analysis Webpage (6.18)

**Comment by amanmdesai** [comment]
With #19, this issue is resolved
